import Head from "next/head";
import Image from "next/image";

function PokemonCardDetails({
  pokemon_name,
  pokemon_ability,
  pokemon_type,
  img_src,
}) {
  return (
    <>
      <Head>
        <title>Pokedex by Nat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Card */}
      <div className="w-full">
        <div className="flex flex-col justify-center items-center p-10">
          <div className="flex flex-col w-72 h-full xl:w-80 2xl:w-96 shadow-xl justify-center items-center bg-base-300 rounded-xl p-6">
            <figure className="">
            <Image src={img_src} width={300} height={300} />

              {/* <Image src={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${pokemon_id}.png`} width={300} height={300} /> */}
            </figure>
            <div className="pb-6">
              <h2 className="card-title">{pokemon_name}</h2>
            </div>
            <div>
              <div className="">
                <div className="font-semibold">Ability</div>
                <div className="flex">{pokemon_ability}</div>
              </div>
              <div className="">
                <div className="font-semibold">Type</div>
                <div className="flex">{pokemon_type}</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

export default PokemonCardDetails;
