import Head from "next/head";
import Image from "next/image";

function PokemonCard({
  pokemon_name,
  pokemon_image,
  pokemon_ability,
  pokemon_type,
  src,
}) {
  return (
    <>
      <Head>
        <title>Pokedex by Nat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Card */}

      <div className="w-full">
        <div className="flex flex-col justify-center items-center p-10">
          <div className="flex flex-col w-72 h-full xl:w-80 2xl:w-96 shadow-xl justify-center items-center bg-base-300 rounded-xl p-10">
            <figure className="">
              <Image src={src} width={300} height={300} />
            </figure>
            <div className="pb-6">
              <h2 className="card-title">{pokemon_name}</h2>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

export default PokemonCard;
