import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export async function getStaticProps() {
  try {
    const res = await fetch("https://iloilo-city-hrs.herokuapp.com/users");
    const users_json = await res.json();

    return {
      props: {
        time: new Date().toISOString(),
        data: users_json,
      },
      revalidate: 1,
    };
  } catch (error) {
    console.error(error);
  }
}

export default function Home({ time, data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pokedex by Nat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Pokedex by Nat!</h1>

        <h3> {time} </h3>

        {data.map((user) => (
          <li key={user.name}>{user.name}</li>
        ))}
      </main>
    </div>
  );
}
